apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec: 
      containers:
      - name: my-pod
        image: lighterlai/docker-demo
        ports:
        - containerPort: 3000