apiVersion: v1
kind: Pod
metadata:
  name: secret-with-mount
  labels:
    app: webserver
spec:
  containers:
  - name: demo-secret-pod
    image: lighterlai/docker-demo
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/creds
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-yaml-demo