apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: webserver
spec:
  containers:
  - name: demo-secret-pod
    image: lighterlai/docker-demo
    ports:
    - containerPort: 3000
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-yaml-demo
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-yaml-demo
          key: password
